#%RAML 1.0
title: MemeMachine API
version: v1.1
baseUri: Http://info3103.cs.unb.ca/
securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication

types:
  Profile:
    type: object
    properties:
      display_name: string

  Image:
    type: object
    properties:
      id: integer
      profile_id: integer
      name: string
      size: string
      extention: string
      uri: string

  Post:
    type: object
    properties:
      id: integer
      profile_id: integer
      image_id: integer
      title: string
      description: string
      dates: datetime
      likes: integer
      dislikes: integer

  Stars:
    type: object
    properties:
      id: integer
      post_id: integer
      profile_id: integer

  Tag:
    type: object
    properties:
      id: integer
      description: string

  Tags:
     type: object
     properties:
       id: integer
       post_id: integer
       tag_id: integer

  Following:
    type: object
    properties:
      id: integer
      following_id: integer
      follower_id: integer

  Comments:
    type: object
    properties:
      id: integer
      comment_body: string
      post_id: integer
      profile_id: integer

/login:
  post:
    queryParameters:
      username: string
      password: string
    responses:
      302:
        body:
          application/json:
            description: redirects you to your profile
      400:
        body:
          application/json:
            description: Bad Request
      500:
        body:
          application/json:
            description: Internal Server Error

/logout:
  delete:
    responses:
      200:
        body:
          application/json:
            description: successfully logged out
      400:
        body:
          application/json:
            description: Bad Request
      403:
        body:
          application/json:
            description: Failed to log out
      500:
        body:
          application/json:
            description: Internal Server Error

/profile:
  get:
    queryParameters:
      profile_id: integer
    responses:
      200:
        body:
          application/json:
            type: Profile
            description: Get a users profile
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      404:
        body:
          application/json:
            description: Profile Not Found
      500:
        body:
          application/json:
            description: Internal Server Error

  put:
    queryParameters:
      profile_id: integer
      display_name: string
    responses:
      302:
        body:
          application/json:
            description: Successfully updated profile redirect back to profile
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error
  /comments:
    get:
      queryParameters:
        profile_id: integer
      responses:
        200:
          body:
            application/json:
              type: Comments[]
              description: list of your comments
        400:
          body:
            application/json:
              description: Bad Request
        401:
          body:
            application/json:
              description: You are not logged in
        404:
          body:
            application/json:
              description: Profile Does Not Exist
        500:
          body:
            application/json:
              description: Internal Server Error


  /posts:
    get:
      responses:
        200:
          body:
            application/json:
              type: Post[]
              description: list of users posts
        400:
          body:
            application/json:
              description: Bad Request
        401:
          body:
            application/json:
              description: You are not logged in
        404:
          body:
            application/json:
              description: Posts Do Not Exist
        500:
          body:
            application/json:
              description: Internal Server Error


  /followers:
    get:
      queryParameters:
        profile_id: integer
      description: If no profile id is passed in then it will return the current users followers
      responses:
        200:
          body:
            application/json:
              type: Profile[]
              description: List of Profiles a specific user is Followed by
        400:
          body:
            application/json:
              description: Bad Request
        401:
          body:
            application/json:
              description: You are not logged in

        500:
          body:
            application/json:
              description: Internal Server Error
  /following:
    get:
      queryParameters:
        profile_id: integer
      description: If no profile id is passed in then it will return the current users followers
      responses:
        200:
          body:
            application/json:
              type: Profile[]
              description: list of Profiles a specific user is following
        400:
          body:
            application/json:
              description: Bad Request
        401:
          body:
            application/json:
              description: You are not logged in
        500:
          body:
            application/json:
              description: Internal Server Error

/post:
  get:
    queryParameters:
      post_id: integer
    responses:
      200:
        body:
          application/json:
            type: Post
            description: Get a specific post
      400:
        body:
          application/json:
            description: Bad Request
      404:
        body:
          application/json:
            description: Post Does Not Exist
      500:
        body:
          application/json:
            description: Internal Server Error

  put:
    queryParameters:
      post_id: integer
      title: string
      description: string
    responses:
      302:
        body:
          application/json:
            description: updates a post redirect back to post
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error

  post:
    queryParameters:
      image_id: integer
      title: string
      description: string
    responses:
      302:
        body:
          application/json:
            description: creates a post redirect back to post
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error
  delete:
    queryParameters:
      post_id: integer
    responses:
      201:
        body:
          application/json:
            description: Deletes a post from access and removes the link to the source image
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error

  /following:
    get:
      responses:
        200:
          body:
            application/json:
              type: Post[]
              description: get a list of most recent posts from followed users
        400:
          body:
            application/json:
              description: Bad Request
        401:
          body:
            application/json:
              description: You are not logged in
        404:
          body:
            application/json:
              description: Posts Do Not Exist
        500:
          body:
            application/json:
              description: Internal Server Error

  /popular:
    get:
      responses:
        200:
          body:
            application/json:
              type: Post[]
              description: get list of most liked posts
        400:
          body:
            application/json:
              description: Bad Request
        404:
          body:
            application/json:
              description: Posts Do Not Exist
        500:
          body:
            application/json:
              description: Internal Server Error

  /starred:
    get:
      responses:
        200:
          body:
            application/json:
              type: Post[]
              description: get list of your starred posts
        400:
          body:
            application/json:
              description: Bad Request
        401:
          body:
            application/json:
              description: You are not logged in
        404:
          body:
            application/json:
              description: Posts Do Not Exist
        500:
          body:
            application/json:
              description: Internal Server Error

  /recent:
    get:
      responses:
        200:
          body:
            application/json:
              type: Post[]
              description: get list of most recent posts
        400:
          body:
            application/json:
              description: Bad Request
        404:
          body:
            application/json:
              description: Posts Do Not Exist
        500:
          body:
            application/json:
              description: Internal Server Error
  /random:
    get:
      responses:
        200:
          body:
            application/json:
              type: Post[]
              description: get list of random posts
        400:
          body:
            application/json:
              description: Bad Request
        404:
          body:
            application/json:
              description: Posts Do Not Exist
        500:
          body:
            application/json:
              description: Internal Server Error

/Img:
  post:
    queryParameters:
      name: string
      size: string
      extention: string
      URI: string
    responses:
      201:
        body:
          application/json:
            description: Image Uploaded Successfully
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      404:
        body:
          application/json:
            description: Missing Image
      500:
        body:
          application/json:
            description: Internal Server Error
  delete:
    queryParameters:
      image_id: integer
    responses:
      200:
        body:
          application/json:
            description: Deletes an image from the file system ONLY if it is not currently in use
      400:
        body:
          application/json:
            description: Image is being referenced by a Post
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error

/Star:
  post:
    queryParameters:
      post_id: integer
    responses:
      201:
        body:
          application/json:
            description: creates a link between current user and a post
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error
  delete:
    queryParameters:
      post_id: integer
    responses:
      200:
        body:
          application/json:
            description: Deletes the link between current user and a post
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error

/Following:
  post:
    queryParameters:
      profile_id: integer
    responses:
      200:
        body:
          application/json:
            description: Creates a following link between current user and another user
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error
  delete:
    queryParameters:
      following_id: integer
    responses:
      200:
        body:
          application/json:
            description: Deletes the link between current user and another user
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error

/Comments:
  get:
    queryParameters:
      profile_id: integer
      post_id: integer
    responses:
      200:
        body:
          application/json:
            type: Comments[]
            description: Returns list of comments connected to a post or a specific user
      400:
        body:
          application/json:
            description: Bad Request
      500:
        body:
          application/json:
            description: Internal Server Error
  put:
    queryParameters:
      comment_body: string
      comment_id: integer
    responses:
      200:
        body:
          application/json:
            description: Update a comment connected to the current authenticated user
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error

  post:
    queryParameters:
      comment_body: string
      post_id: integer
    responses:
      201:
        body:
          application/json:
            description: Creates and links a comment to a post authored by currently authenticated user
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error

  delete:
    queryParameters:
      comment_id: integer
    responses:
      200:
        body:
          application/json:
            description: delete a post connected to the current authenticated user
      400:
        body:
          application/json:
            description: Bad Request
      401:
        body:
          application/json:
            description: You are not logged in
      500:
        body:
          application/json:
            description: Internal Server Error
